### PR TITLE
fix: corrected project/unproject when tilting/rotating a google vector map

### LINKED ISSUE #76: Cannot select points in Google Maps Adapter when view is rotated/tilted
When rotating/tilting a (vector) map using the Google Maps adapter, selection breaks. It seems like `project` and `unproject` in google-maps-adapter does not take rotation/tilting into account.

I did a quick test with replacing the project/unproject code with `projection.fromLatLngToContainerPixel` and `projection.fromContainerPixelToLatLng` which seems to work better, but I'm unsure if there's reasons not to use those instead of the custom projection code?

### PR DESCRIPTION
**Pull request by anderswi**
Fixes #76, by using the built in fromContainerPixelToLatLng / fromLatLngToContainerPixel.

### CODE REVIEW

File: development/src/index.ts [hunk 1]
```diff
@@ -334,6 +334,7 @@ const example = {
 					center: { lat: this.lat, lng: this.lng },
 					zoom: this.zoom,
 					clickableIcons: false,
+					mapId: process.env.GOOGLE_MAP_ID,
```
Comment (anderswi) [inline development/src/index.ts:337]: You can load vector maps in Google Maps by providing your own map id... If left undefined it will default to the standard map.

**Comment by JamesLMilner** [comment]
Thanks! This seems to be working from my testing. I'll merge it in.

Screenshot_20230917_010805-1
